# Generated by Django 3.1.1 on 2020-09-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book1',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
