# Generated by Django 3.1.1 on 2020-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_book2'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book3',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
