# Generated by Django 3.1.1 on 2020-09-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200923_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('book', models.FileField(upload_to='')),
                ('book1', models.FileField(upload_to='')),
                ('book2', models.FileField(upload_to='')),
                ('book3', models.FileField(upload_to='')),
                ('book4', models.FileField(upload_to='')),
                ('book5', models.FileField(upload_to='')),
            ],
        ),
    ]
