# Generated by Django 3.1.1 on 2020-09-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_book1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book1',
            old_name='book',
            new_name='book10',
        ),
        migrations.RenameField(
            model_name='book1',
            old_name='book1',
            new_name='book11',
        ),
        migrations.RenameField(
            model_name='book1',
            old_name='book2',
            new_name='book6',
        ),
        migrations.RenameField(
            model_name='book1',
            old_name='book3',
            new_name='book7',
        ),
        migrations.RenameField(
            model_name='book1',
            old_name='book4',
            new_name='book8',
        ),
        migrations.RenameField(
            model_name='book1',
            old_name='book5',
            new_name='book9',
        ),
    ]
