# Generated by Django 3.1.1 on 2020-09-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200923_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book13',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
