# Generated by Django 3.1.1 on 2020-09-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_book_book13'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book1',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book13',
            new_name='book6',
        ),
    ]
